let settings={primary_color:'#9B7EDE',secondary_color:'#F4C7D8',accent_color:'#D9B86C',background_color:'#FFF9F5',text_color:'#3E3348',store_name:'Leva',arabic_name:'ليڤـا',tagline:'فرحة عمر، بأنامل ليڤـا تُرسم',description:'توزيعات وهدايا وتفاصيل مميزة للمناسبات السعيدة.',whatsapp:'966533817655'};
const $=id=>document.getElementById(id);function showOk(){$('ok').style.display='block';setTimeout(()=>$('ok').style.display='none',1600)}function err(msg){$('loginError').textContent=msg;$('loginError').style.display='block'}
function show(id,b){document.querySelectorAll('#app section.card').forEach(s=>s.classList.add('hidden'));$(id).classList.remove('hidden');document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');if(id==='orders')loadOrders();}
async function isAdmin(){if(!window.LEVA_SUPABASE_READY)return false;const {data:{user}}=await supabaseClient.auth.getUser();if(!user)return false;const {data,error}=await supabaseClient.rpc('is_admin');return !error&&data===true}
async function init(){if(!window.LEVA_SUPABASE_READY){err('ملف supabase-config.js لم يُضبط بعد. ضعي Project URL و Publishable key.');return}const {data:{session}}=await supabaseClient.auth.getSession();if(session&&await isAdmin())return openApp();if(session)await supabaseClient.auth.signOut();}
function openApp(){$('loginCard').classList.add('hidden');$('app').classList.remove('hidden');loadSettings();loadProducts();}
$('loginBtn').onclick=async()=>{ $('loginError').style.display='none';const {error}=await supabaseClient.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(error){err('بيانات الدخول غير صحيحة أو الحساب غير مُنشأ بعد.');return}if(!await isAdmin()){await supabaseClient.auth.signOut();err('هذا الحساب ليس ضمن حسابات إدارة المتجر.');return}openApp()};
$('logoutBtn').onclick=()=>supabaseClient.auth.signOut().then(()=>location.reload());
async function loadSettings(){const {data}=await supabaseClient.from('store_settings').select('*').eq('id',true).single();if(data)settings=data;['primary','secondary','accent','cream','text'].forEach((k,i)=>$(k).value=[settings.primary_color,settings.secondary_color,settings.accent_color,settings.background_color,settings.text_color][i]);$('bn').value=settings.store_name||'';$('ba').value=settings.arabic_name||'';$('bw').value=settings.whatsapp||'';$('bt').value=settings.tagline||'';$('bd').value=settings.description||''}
async function saveTheme(){const payload={primary_color:$('primary').value,secondary_color:$('secondary').value,accent_color:$('accent').value,background_color:$('cream').value,text_color:$('text').value,updated_at:new Date().toISOString()};const {data,error}=await supabaseClient.from('store_settings').update(payload).eq('id',true).select().single();if(error)return alert('تعذر حفظ الألوان: '+error.message);if(!data)return alert('لم يتم العثور على إعدادات المتجر.');showOk()}
async function saveBrand(){const payload={store_name:$('bn').value.trim(),arabic_name:$('ba').value.trim(),whatsapp:$('bw').value.replace(/\D/g,''),tagline:$('bt').value.trim(),description:$('bd').value.trim(),updated_at:new Date().toISOString()};const {error}=await supabaseClient.from('store_settings').update(payload).eq('id',true);if(error)return alert(error.message);showOk()}
async function loadProducts(){const {data,error}=await supabaseClient.from('products').select('*').order('created_at',{ascending:false});if(error)return alert(error.message);$('plist').innerHTML=data.map(p=>`<div class="product"><b>${p.name}</b><div class="muted">${p.price} ر.س · ${p.category} · ${p.active?'ظاهر':'مخفي'}</div><div class="muted">${p.description||''}</div><div class="row" style="margin-top:8px"><button class="btn ghost" onclick="toggleProduct('${p.id}',${!p.active})">${p.active?'إخفاء':'إظهار'}</button><button class="danger" onclick="deleteProduct('${p.id}')">حذف</button></div></div>`).join('')||'<p>لا توجد منتجات.</p>'}
async function addProduct(){const name=$('pn').value.trim(),price=Number($('pp').value||0),category=$('pc').value,description=$('pd').value.trim(),file=$('pfile').files[0];if(!name)return alert('اكتبي اسم المنتج');let image_url='';if(file){const ext=file.name.split('.').pop().toLowerCase();const path=`${crypto.randomUUID()}.${ext}`;const {error:up}=await supabaseClient.storage.from('products').upload(path,file,{upsert:false});if(up)return alert('تعذر رفع الصورة: '+up.message);const {data:urlData}=supabaseClient.storage.from('products').getPublicUrl(path);image_url=urlData.publicUrl}const {error}=await supabaseClient.from('products').insert({name,category,price,description,image_url,active:true});if(error)return alert(error.message);$('pn').value='';$('pp').value='';$('pd').value='';$('pfile').value='';showOk();loadProducts()}
async function toggleProduct(id,active){const {error}=await supabaseClient.from('products').update({active}).eq('id',id);if(error)return alert(error.message);loadProducts()}
async function deleteProduct(id){if(!confirm('حذف المنتج نهائيًا؟'))return;const {error}=await supabaseClient.from('products').delete().eq('id',id);if(error)return alert(error.message);loadProducts()}
async function loadOrders(){const {data,error}=await supabaseClient.from('orders').select('*').order('created_at',{ascending:false});if(error){$('olist').textContent=error.message;return}$('olist').innerHTML=data.map(o=>`<div class="order"><b>طلب #${o.id}</b><div>${o.customer_name} · ${o.customer_phone}</div><div>${Number(o.total).toFixed(2)} ر.س · ${o.status}</div><div class="muted">${new Date(o.created_at).toLocaleString('ar-SA')}</div><pre style="white-space:pre-wrap">${JSON.stringify(o.items,null,2)}</pre><button class="btn primary" onclick="markOrder('${o.id}','processing')">قيد التجهيز</button> <button class="btn ghost" onclick="markOrder('${o.id}','completed')">مكتمل</button></div>`).join('')||'<p>لا توجد طلبات حتى الآن.</p>'}
async function markOrder(id,status){const {error}=await supabaseClient.from('orders').update({status}).eq('id',id);if(error)return alert(error.message);loadOrders()}
init();
