const defaults={
 brand:{name:'Leva',arabicName:'ليڤـا',tagline:'فرحة عمر، بأنامل ليڤـا تُرسم',description:'توزيعات وهدايا وتفاصيل مميزة للمناسبات السعيدة.'},
 theme:{primary:'#9B7EDE',secondary:'#F4C7D8',accent:'#D9B86C',cream:'#FFF9F5',text:'#3E3348'},
 whatsapp:'966533817655',
 products:[
 {id:1,name:'توزيعات التخرج الكلاسيكية',price:15,cat:'grad',emoji:'🎓',desc:'توزيعات أنيقة للتخرج قابلة للتخصيص بالاسم والعبارة.'},
 {id:2,name:'توزيعات استقبال المواليد',price:12,cat:'birth',emoji:'🧸',desc:'تفاصيل لطيفة لاستقبال المولود مع إمكانية اختيار الألوان.'},
 {id:3,name:'توزيعات المناسبات',price:10,cat:'gifts',emoji:'🎁',desc:'توزيعات ناعمة للمناسبات السعيدة بتفاصيل ليڤـا.'},
 {id:4,name:'لوحات فنية وديكور',price:150,cat:'gifts',emoji:'🖼️',desc:'لوحات ديكور فنية بلمسة ثلاثية الأبعاد وتصاميم خاصة.'},
 {id:5,name:'بروشات تخرج مخصصة',price:18,cat:'grad',emoji:'🏅',desc:'بروشات بأسماء الخريجين وتصاميم تناسب المناسبة.'},
 {id:6,name:'علب استقبال مواليد',price:25,cat:'birth',emoji:'🎀',desc:'علبة استقبال متكاملة بتفاصيل ناعمة.'},
 {id:7,name:'هدايا مناسبات',price:35,cat:'gifts',emoji:'💝',desc:'هدية جاهزة أو مخصصة حسب مناسبتك.'},
 {id:8,name:'تصميم خاص',price:50,cat:'gifts',emoji:'🦋',desc:'فكرة خاصة بك تتحول إلى تصميم يحمل تفاصيل مناسبتك.'}
]};
let config=JSON.parse(localStorage.getItem('levaConfig')||'null')||defaults;
let products=config.products;
let cart=JSON.parse(localStorage.getItem('levaCart')||'[]');
const productsEl=document.getElementById('products'),cartCount=document.getElementById('cartCount'),cartDrawer=document.getElementById('cartDrawer'),overlay=document.getElementById('overlay'),cartItems=document.getElementById('cartItems'),cartTotal=document.getElementById('cartTotal'),modal=document.getElementById('productModal'),modalContent=document.getElementById('modalContent');
function applyConfig(){const r=document.documentElement;Object.entries(config.theme).forEach(([k,v])=>r.style.setProperty('--'+k,v));const logo=document.querySelector('.logo');if(logo)logo.innerHTML=`<span>${config.brand.name}</span><small>${config.brand.arabicName}</small>`;const heroH=document.querySelector('.hero h1');if(heroH)heroH.innerHTML=config.brand.tagline.replace('،','،<br>');const heroP=document.querySelector('.hero-copy p');if(heroP)heroP.innerHTML=config.brand.description;const customBtn=document.querySelector('.custom .btn');if(customBtn)customBtn.href=`https://wa.me/${config.whatsapp}`;document.title=`${config.brand.name} | ${config.brand.arabicName}`}
function renderProducts(filter='all'){const list=filter==='all'?products:products.filter(p=>p.cat===filter);productsEl.innerHTML=list.map(p=>`<article class="product"><div class="product-img" onclick="openProduct('${p.id}')">${p.image?`<img src="${p.image}" alt="${p.name}">`:p.emoji||'🌸'}</div><div class="product-body"><h3>${p.name}</h3><div class="price">${p.price} ر.س</div><div class="product-actions"><button class="add" onclick="addToCart('${p.id}')">أضف للسلة 🛍</button><button class="details" onclick="openProduct('${p.id}')">التفاصيل</button></div></div></article>`).join('')}
function saveCart(){localStorage.setItem('levaCart',JSON.stringify(cart));updateCart()}
function addToCart(id){const x=cart.find(i=>String(i.id)===String(id));if(x)x.qty++;else cart.push({id,qty:1});saveCart();openCart()}
function updateCart(){cart=cart.filter(x=>products.some(p=>String(p.id)===String(x.id)));cartCount.textContent=cart.reduce((s,x)=>s+x.qty,0);cartItems.innerHTML=cart.length?cart.map(x=>{const p=products.find(y=>String(y.id)===String(x.id));return `<div class="cart-line"><div class="cart-thumb">${p.image?`<img src="${p.image}">`:p.emoji||'🌸'}</div><div><h4>${p.name}</h4><div class="qty"><button onclick="changeQty('${p.id}',-1)">−</button><span>${x.qty}</span><button onclick="changeQty('${p.id}',1)">+</button></div></div><div><b>${p.price*x.qty} ر.س</b><br><button class="remove" onclick="removeItem('${p.id}')">حذف</button></div></div>`}).join(''):'<div class="empty">سلتك فارغة حاليًا ♡<br>اختاري شيئًا جميلًا ليڤـا.</div>';cartTotal.textContent=cart.reduce((s,x)=>s+products.find(p=>String(p.id)===String(x.id)).price*x.qty,0)+' ر.س'}
function changeQty(id,n){const x=cart.find(i=>String(i.id)===String(id));if(x){x.qty+=n;if(x.qty<=0)cart=cart.filter(i=>String(i.id)!==String(id))}saveCart()}
function removeItem(id){cart=cart.filter(i=>String(i.id)!==String(id));saveCart()}
function openCart(){cartDrawer.classList.add('open');overlay.classList.add('show')}function closeCart(){cartDrawer.classList.remove('open');overlay.classList.remove('show')}
function openProduct(id){const p=products.find(x=>String(x.id)===String(id));if(!p)return;modalContent.innerHTML=`<div class="modal-content"><div class="modal-img">${p.image?`<img src="${p.image}" alt="${p.name}">`:p.emoji||'🌸'}</div><div><span class="mini-title">Leva | ليڤـا</span><h2>${p.name}</h2><p>${p.desc||''}</p><h3 class="price">${p.price} ر.س</h3><button class="btn" onclick="addToCart('${p.id}');closeModal()">أضيفيه للسلة 🛍</button></div></div>`;modal.classList.add('show');overlay.classList.add('show')}
function closeModal(){modal.classList.remove('show');overlay.classList.remove('show')}
async function loadCloudData(){if(!window.LEVA_SUPABASE_READY||!window.supabaseClient)return;try{const {data:s,error:se}=await supabaseClient.from('store_settings').select('*').limit(1).maybeSingle();if(!se&&s){config.brand={name:s.store_name||config.brand.name,arabicName:s.arabic_name||config.brand.arabicName,tagline:s.tagline||config.brand.tagline,description:s.description||config.brand.description};config.theme={primary:s.primary_color||config.theme.primary,secondary:s.secondary_color||config.theme.secondary,accent:s.accent_color||config.theme.accent,cream:s.background_color||config.theme.cream,text:s.text_color||config.theme.text};config.whatsapp=s.whatsapp||config.whatsapp}const {data:p,error:pe}=await supabaseClient.from('products').select('*').eq('active',true).order('created_at',{ascending:false});if(!pe&&p&&p.length){products=p.map(x=>({id:x.id,name:x.name,price:Number(x.price),cat:x.category,desc:x.description||'',image:x.image_url||'',emoji:'🌸'}));config.products=products}localStorage.setItem('levaConfig',JSON.stringify(config));applyConfig();renderProducts();updateCart()}catch(e){console.warn('Supabase load skipped',e)}}
async function createOrderOnCloud(customerName,phone,notes){if(!window.LEVA_SUPABASE_READY||!window.supabaseClient)return null;const items=cart.map(x=>{const p=products.find(y=>String(y.id)===String(x.id));return {product_id:p.id,name:p.name,price:p.price,qty:x.qty}});const total=items.reduce((s,x)=>s+x.price*x.qty,0);const {data,error}=await supabaseClient.from('orders').insert({customer_name:customerName,customer_phone:phone,items,total,status:'new',notes:notes||null}).select('id').single();if(error)throw error;return {id:data.id,total}}
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderProducts(b.dataset.filter)}));document.querySelectorAll('[data-filter]').forEach(a=>a.addEventListener('click',()=>{const f=a.dataset.filter;if(f){document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x.dataset.filter===f));renderProducts(f)}}));document.getElementById('cartBtn').onclick=openCart;document.getElementById('closeCart').onclick=closeCart;document.getElementById('closeModal').onclick=closeModal;overlay.onclick=()=>{closeCart();closeModal()};
document.getElementById('checkout').onclick=async()=>{if(!cart.length){alert('السلة فارغة');return}const lines=cart.map(x=>{const p=products.find(y=>String(y.id)===String(x.id));return `• ${p.name} × ${x.qty} = ${p.price*x.qty} ر.س`}).join('\n');const total=cart.reduce((s,x)=>s+products.find(p=>String(p.id)===String(x.id)).price*x.qty,0);let customerName=prompt('اكتبي اسمك لإرسال الطلب:');if(!customerName)return;let phone=prompt('اكتبي رقم الجوال للتواصل:');if(!phone)return;const waBase=`https://wa.me/${config.whatsapp}`;let waWindow=null;try{waWindow=window.open(waBase,'_blank');}catch(e){}let orderId='';try{const result=await createOrderOnCloud(customerName,phone,'طلب من المتجر عبر واتساب');if(result)orderId=`\nرقم الطلب: ${result.id}`}catch(e){console.error(e);alert('تعذر حفظ الطلب في قاعدة البيانات، لكن سيتم فتح WhatsApp لإرسال الطلب.')}const msg=`مرحبًا Leva 🌷 أود طلب:\n${lines}\n\nالإجمالي: ${total} ر.س${orderId}\nالاسم: ${customerName}\nالجوال: ${phone}\nأرغب بتأكيد الطلب.`;const waUrl=`${waBase}?text=${encodeURIComponent(msg)}`;if(waWindow&&!waWindow.closed){try{waWindow.location.href=waUrl;waWindow.focus();return}catch(e){}}window.location.href=waUrl};
document.getElementById('searchBtn').onclick=()=>{const q=prompt('اكتبي اسم المنتج الذي تبحثين عنه:');if(!q)return;renderSearch(products.filter(p=>p.name.includes(q.trim())))};function renderSearch(found){productsEl.innerHTML=found.length?found.map(p=>`<article class="product"><div class="product-img" onclick="openProduct('${p.id}')">${p.image?`<img src="${p.image}">`:p.emoji||'🌸'}</div><div class="product-body"><h3>${p.name}</h3><div class="price">${p.price} ر.س</div><div class="product-actions"><button class="add" onclick="addToCart('${p.id}')">أضف للسلة 🛍</button><button class="details" onclick="openProduct('${p.id}')">التفاصيل</button></div></div></article>`).join(''):'<p>لم نجد منتجًا بهذا الاسم.</p>'}
applyConfig();renderProducts();updateCart();loadCloudData();
